manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 6e7e0de2b621073392816b284ab4931bee709ee8
      import: app/west.yml
  self:
    path: config
